version: '3.8'

services:
  api-gateway:
    build: ../api-gateway
    ports:
      - "4000:4000"
    depends_on:
      - auth-service
    env_file:
      - ../service/auth-service/.env
    networks:
      - microservice-net

  auth-service:
    build: ../service/auth-service
    ports:
      - "3004:3004"
    networks:
      - microservice-net

networks:
  microservice-net:
    driver: bridge